# This workflow will build a package using Gradle and then publish it to OSSRH when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Publish to OSSRH when released

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Extract secring.gpg to sign files
      run: pwd && echo -n $HW | base64 --decode > myfile.txt && cat myfile.txt && ls -al

    - name: Publish to OSSRH
      run: ./gradlew publish
      env:
        OSSRH_PWD: ${{ secrets.OSSRH_PWD }}
