micronaut:
  application:
    name: micronaut-camunda-example
  servlet:
    name: "Default"
    mapping: "/default/*"
  router:
    static-resources:
      webjars:
        enabled: true
        paths:
          - "classpath:/META-INF/resources/webjars/camunda"
          - "classpath:/META-INF/resources/"
        mapping: "/**"

camunda.bpm:
  telemetry.initializeTelemetry: true