micronaut:
  application:
    name: micronaut-camunda-example
  router:
    static-resources:
      webjars:
        enabled: true
        paths:
          - "classpath:/META-INF/resources/webjars/camunda"
          - "classpath:/META-INF/resources/plugin"
        mapping: /webjars/**

camunda.bpm.telemetry.initializeTelemetry: true
