micronaut:
  application:
    name: micronaut-camunda-example
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/forms/**"
        paths: classpath:forms
camunda:
  admin-user:
    id: admin
    password: admin
  generic-properties:
    properties:
      initialize-telemetry: true
  webapps:
    enabled: true
  rest:
    enabled: true
  filter:
    create: "All tasks"
