micronaut:
  application:
    name: micronaut-camunda-example
camunda:
  generic-properties:
    properties:
      initialize-telemetry: true
  webapps:
    enabled: true
  rest:
    enabled: true
  filter:
    create: "All tasks"
